### ISSUE TITLE
They wont work for 1.9.3

### ISSUE THREAD

**Issue by SonixS** [ZeWhiteHatHacker/krunker-hacks#1]
I launched it and It wont work for season 2.

**Comment by ZeWhiteHatHacker** [comment]
Hey there, sorry for the late response was on holiday, I haven't update the hack for the latest versions (currently 19.7/season 2) I am doing my best to try and pacth the hack for season 2! Good luck

PS: I recommend you [subscribe](https//bit.ly/BayMaxYT) or watch this GitHub repo.
